development: &development
  adapter: postgresql
  encoding: utf8
  database: vimshop_locations_development
  username:
  password:

test:
  <<: *development
  database: vimshop_locations_test

cucumber:
  <<: *development
  database: vimshop_locations_cucumber

production:
  <<: *development
  database: vimshop_locations_production
